server:
  port: 8086

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/accounts_transfer}
    username: ${JDBC_USER:user}
    password: ${JDBC_PASS:user}
  jpa:
    show-sql: ${SHOW_SQL:true}
